# Generated by Django 6.0.3 on 2026-03-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='materials',
            field=models.FileField(upload_to='courses/'),
        ),
    ]
