# Generated by Django 6.0.3 on 2026-03-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollment2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment2',
        ),
    ]
